config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :questions do
    resources :comments
    resources :options
  end

end

app/models/comment.rb
class Comment<ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  default_scope {order('created_at DESC')}
end

app/models/option.rb
class Option < ActiveRecord::Base
  default_scope { order('id DESC') }
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :options, :dependent => :destroy
  accepts_nested_attributes_for :options


  def calculate_percentage
    option1 = self.options[0].votes.to_f
    option2 = self.options[1].votes.to_f
    if option1 + option2 != 0
      percent1 = (option1/(option1 + option2)*100).floor
      percent2 = (option2/(option1 + option2)*100).floor
    else
      percent1 = 0
      percent2 = 0
    end
    return [percent1, percent2]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @question = Question.find(params[:question_id])
    @comment.update(question_id: @question.id)
    current_user.comments.push(@comment)
    if @comment.save
      respond_to do |format|
        format.html {redirect_to '/'}
        format.js

      end
    else
      render :new
    end
  end


  private def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all

  end
end

app/controllers/options_controller.rb
class OptionsController<ApplicationController
  def new
    @option = Option.new
  end

  def update
    @option = Option.find(params[:id])
    @question = Question.find(@option.question_id)
    @option.votes+=1
    @option.save
    respond_to do |format|
      format.html { redirect_to '/' }
      format.js
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
    2.times {@question.options.build}
  end

  def create
    @question = Question.new(question_params)
    current_user.questions.push(@question)
    if @question.save
      respond_to do |format|
      format.html {redirect_to '/'}
      format.js
      end
    else
      render :new
    end
  end


  private def question_params
    params.require(:question).permit(:description, options_attributes: [:name, :image_url])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div id="comment_form_<%= @question.id %>">
<%= simple_form_for [@question, @comment], remote: true do |f| %>
  <%= f.text_field :content, placeholder: "Comment" %>
  <span id="create_comment_link_<%= @question.id %>"><%= f.submit %></span>
<% end %>
</div>

app/views/comments/create.js.erb
$('#comment_form_<%= @question.id %>').hide().after($('#comment_container_<%= @question.id %>').prepend('\
<div class="well">\
  <%= User.find(@comment.user_id).email %>\
  <%= @comment.content %>\
</div> '));
$("comment_button_<%= @question.id %>").append('#new_question_comment_link_<%= @question.id %>').after($('#new_question_comment_link_<%= @question.id %>').show());

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/new.js.erb
$('#new_question_comment_link_<%= @question.id %>').hide().after('<%= j render("form") %>');

app/views/home/index.html.erb
HOMEPAGE!!!!!!!
<br><br><br>
<% if current_user %>
<% @questions.each do |question| %>
  <div class= "container text-center">
    <h3><span class = "question-text"> <%= question.description %> </span></h3>
  <br>
  <br>
  <br>
    <div class= "row">
      <% question.options.order(:created_at).each do |option| %>
        <div class="col-md-4">
          <figure>
            <%= link_to(question_option_path(question, option), :method => :patch, remote: true) do %>
              <%= image_tag option.image_url, width: "250", height: "250" %>
              <em><figcaption><%= option.name %></figcaption></em>
            <% end %>
          </figure>
        </div>
      <% end %>
    <div class="col-md-4" id="comment_container_<%= question.id %>" style="overflow:scroll; height:225px;">
      <% question.comments.each do |comment| %>
        <div class="well">
          <%= User.find(comment.user_id).email %>
          <%= comment.content %>
        </div>
      <% end %>
    </div>
    <div id="comment_button_<%= question.id %>">
      <%= link_to "New Comment", new_question_comment_path(question), id: "new_question_comment_link_" + question.id.to_s, class: "btn btn-warning", remote: true %>
    </div>
    </div>
  </div>
<div id="percentage_calculate_<%= question.id %>" class="row" >

</div>


<% end %>
<footer class="footer">
  <div class="container">
    <%= link_to "New Question", new_question_path, id: "new_question_link", class: "btn btn-info", remote: true %>
  </div>
</footer>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsGrosser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] %>
  <%= flash[:alert] %>

  <nav class="navbar navbar-default navbar-fixed-top">
    <ul class="nav navbar-nav">

      <li class="pull-left"><%= link_to "What's Grosser", "/" %></li>

      <% if user_signed_in? %>
      <li class="pull-right">
        <span>
          <!-- <%# if current_user.admin? %>
          Welcome admin, <i><%#= current_user.username %></i>! |
          <%# else %> -->
          You are logged in as <i><%= current_user.email %></i>! |
          <!-- <%# end %> -->

          <%= link_to "Logout", destroy_user_session_path, method: :delete %>

        </span>
      </li>
      <% else %>
      <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
      <li class="pull-right"><%= link_to "Signup",  new_user_registration_path %></li>
      <% end %>

    </ul>
  </nav>


<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/options/_percent_bar.html.erb
<div id = "percentage_calculate_<%= @question.id %>" class ="row" >
<h1> <%= @question.calculate_percentage[0] %>%
  <span class="percentage"> <%= @question.calculate_percentage[1] %>%</span> </h1>
  <div class="progress">
    <div class="progress-bar progress-bar-success" style="width:<%= @question.calculate_percentage[0] %>%"></div>
    <div class="progress-bar progress-bar-info" style="width:<%= @question.calculate_percentage[1] %>%" ></div>
  </div>
</div>

app/views/options/update.html.erb
<%= render 'percent_bar' %>

app/views/options/update.js.erb
$('#percentage_calculate_<%= @question.id  %>').html('<%= j render("percent_bar") %>');

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f|%>
  <%= f.text_field :description, placeholder: "Question" %>
    <%= f.simple_fields_for :options do |option| %>
    <%= render 'questions/option_fields', :f => option %>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/questions/_option_fields.html.erb
  <%= f.input :name %>
  <%= f.input :image_url %>

app/views/questions/new.html.erb
<%= render "form" %>

app/views/questions/new.js.erb
$('#new_question_link').hide().after('<%= j render("form") %>');

app/views/questions/options/_percent_bar.html.erb
<h1> <%= question.calculate_percentage[0] %>%
  <span class="percentage"> <%= question.calculate_percentage[1] %>%</span> </h1>
  <div class="progress">
    <div class="progress-bar progress-bar-success" style="width:<%= question.calculate_percentage[0] %>%"></div>
    <div class="progress-bar progress-bar-info" style="width:<%= question.calculate_percentage[1] %>%" ></div>
  </div>
  

app/views/questions/options/update.js.erb
$('.percentage_calculate').replace('<%= j render("percent_bar") %>');